### ISSUE TITLE
Promotion to Sonatype fails with "URI is not absolute"

### ISSUE THREAD

**Issue by snicoll** [spring-io/concourse-release-scripts#26]
Upgrading to `0.3.3` fails to promote to Sonatype:

```
/21.1#L61b0f530:41)2022-02-17 08:22:50.763 ERROR 20 --- [           main] o.s.boot.SpringApplication               : Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:785) [spring-boot-2.5.1.jar!/:2.5.1]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:772) [spring-boot-2.5.1.jar!/:2.5.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) [spring-boot-2.5.1.jar!/:2.5.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.1.jar!/:2.5.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.1.jar!/:2.5.1]
	at io.spring.concourse.releasescripts.Application.main(Application.java:28) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_322]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_322]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_322]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_322]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [concourse-release-scripts.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [concourse-release-scripts.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [concourse-release-scripts.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [concourse-release-scripts.jar:na]
Caused by: java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(URI.java:1088) ~[na:1.8.0_322]
	at org.springframework.http.client.SimpleClientHttpRequestFactory.createRequest(SimpleClientHttpRequestFactory.java:145) ~[spring-web-5.3.8.jar!/:5.3.8]
	at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:124) ~[spring-web-5.3.8.jar!/:5.3.8]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:772) ~[spring-web-5.3.8.jar!/:5.3.8]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:751) ~[spring-web-5.3.8.jar!/:5.3.8]
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:377) ~[spring-web-5.3.8.jar!/:5.3.8]
	at io.spring.concourse.releasescripts.sonatype.SonatypeService.artifactsPublished(SonatypeService.java:143) ~[classes!/:na]
	at io.spring.concourse.releasescripts.sonatype.SonatypeService.publish(SonatypeService.java:111) ~[classes!/:na]
	at io.spring.concourse.releasescripts.command.PublishToCentralCommand.run(PublishToCentralCommand.java:76) ~[classes!/:na]
	at io.spring.concourse.releasescripts.command.CommandProcessor.run(CommandProcessor.java:55) ~[classes!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:782) [spring-boot-2.5.1.jar!/:2.5.1]
	... 13 common frames omitted
```

Downgrading to `0.3.2` fixes the issue. We're suspecting this to be the problem: https://github.com/spring-io/concourse-release-scripts/blob/b2af3a1e97a1f78d19b2e687ecc7d3a94523eb51/src/main/java/io/spring/concourse/releasescripts/sonatype/SonatypeService.java#L98-L104

**Comment by bclozel** [comment]
Is that a deplucate of #18 ?
